#!/bin/bash

# Copyright 2013 Patrick J. Verner, Waupaca, WI, USA
# Copyright 2024 crims0n <crims0n@minios.dev>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Writen by Patrick Verner and J Vasquez for Parted Magic

# Set text domain
export TEXTDOMAIN="chntpw-gui"

ps aux | grep "[g]tkdialog --program=CHNTPW_MENU" && exit

export TERMINAL=$(update-alternatives --query x-terminal-emulator | grep 'Value: ' | cut -d ' ' -f 2)
export WIDTH="400"
export TITLE=$(gettext "CHNTPW Menu")

export TEXT=$(gettext "Pick a method to change or reset your Windows password.")

export CHNTPW_1=$(gettext "_Not Hibernated - Windows PC was Shut Down.")
export CHNTPW_2=$(gettext "_Hibernated - Windows PC was rebooted.")
export PCLOGINNOW=$(gettext "_PC Login Now - Older GUI program.")

export ERASE_MENU='
<window title="'$TITLE'" window-position="1">
	<vbox border-width="15" spacing="10">
		<text width_request="'$WIDTH'" use-markup="true" xalign="0"><label>'$TEXT'</label></text>
		<hseparator></hseparator>
			<hbox homogeneous="true">
			<vbox border-width="15">
            			<button height-request="35" use-underline="true" xalign="0">
					<label>'$CHNTPW_1'</label>
					<action>chntpw-gui-reset &</action><action>exit:Exit</action>
				</button>
            			<button height-request="35" use-underline="true" xalign="0">
					<label>'$CHNTPW_2'</label>
					<action>chntpw-gui-test &</action><action>exit:Exit</action>
				</button>
			</vbox>
			</hbox>
			<hbox>
			<button cancel></button>
			</hbox>
	</vbox>
</window>
'

gtkdialog --program=ERASE_MENU
